---
# - name: install docker repository
#   yum_repository:
#     name: docker
#     description: docker repo
#     baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
#     gpgkey: https://download.docker.com/linux/centos/gpg
- name: register docker repository
  yum:
    name: https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-17.09.0.ce-1.el7.centos.x86_64.rpm

- name: install docker
  yum:
    name: docker-ce

- name: setting http_proxy
  file:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  when: used_proxy

- name: setting https_proxy
  file:
    src: https-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/https-proxy.conf
  when: used_proxy

- name: start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.17.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

# - name: docker-compose up
#   docker_service:
#     project_src: /workspace/docker

#TODO 冪等性
- name: docker-compose up
  shell: /usr/local/bin/docker-compose up -d
  args:
    chdir: /workspace/docker