# -*- mode: ruby -*-
# vi: set ft=ruby :
Dotenv.load

Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.3"

  # config.proxy.http = ENV['HTTP_PROXY']
  # config.proxy.https = ENV['HTTPS_PROXY']
  # config.proxy.no_proxy = "localhost,127.0.0.1"

  config.vm.network "forwarded_port", guest: 3001, host: 3001
  config.vm.network "forwarded_port", guest: 3002, host: 3002

  config.vm.synced_folder "../docker", "/workspace/docker"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.verbose = "-vvv"
    ansible.extra_vars = {
      git_user_name: ENV['GIT_USER_NAME'],
      git_user_email: ENV['GIT_USER_EMAIL'],
      used_proxy: ENV['USED_PROXY'],
      http_proxy: ENV['HTTTP_PROXY'],
      https_proxy: ENV['HTTTPS_PROXY']
    }
    ansible.inventory_path = "ansible/inventory"
  end
end
