---
- name: install git
  yum:
    name: git

- name: setting git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  with_items:
    - { name: 'user.name', value: "{{ git_user_name }}" }
    - { name: 'user.email', value: "{{ git_user_email }}" }

- name: install tmux
  yum:
    name: tmux